-- +goose Up

CREATE TABLE IF NOT EXISTS gallery
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content      TEXT         NOT NULL,
    content_hash VARCHAR(32)  NOT NULL,
    author_id    BIGINT       NOT NULL,
    images       JSONB        NOT NULL DEFAULT '[]'::jsonb,
    is_published BOOLEAN      DEFAULT FALSE,
    is_top       BOOLEAN      DEFAULT FALSE,
    ext_info     JSONB,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ  DEFAULT now(),
    deleted_at   TIMESTAMPTZ,

    FOREIGN KEY (author_id) REFERENCES app_user (id)
);

CREATE INDEX IF NOT EXISTS idx_gallery_published_created_at ON gallery (
    is_published,
    is_top DESC,
    created_at DESC
);

INSERT INTO
    nav_menu (
        name,
        url,
        icon,
        sort,
        parent_id,
        created_at,
        updated_at
    )
SELECT '日常', '/gallery', 'images', 25, NULL, NOW (), NOW ()
WHERE
    NOT EXISTS (
        SELECT 1
        FROM nav_menu
        WHERE
            name = '日常'
            AND parent_id IS NULL
            AND deleted_at IS NULL
    );

-- +goose Down
DELETE FROM nav_menu WHERE name = '日常' AND parent_id IS NULL;

DROP TABLE IF EXISTS gallery;